# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x63onfig.proto\x12\x06protos\"\xf8\x03\n\x0bTrainConfig\x12\x17\n\x05model\x18\x01 \x01(\t:\x08renet101\x12%\n\x0ftrain_data_root\x18\x02 \x01(\t:\x0c./data/train\x12#\n\x0etest_data_root\x18\x03 \x01(\t:\x0b./data/test\x12.\n\x0fload_model_path\x18\x04 \x01(\t:\x15\x63heckpoints/model.pth\x12\x17\n\nbatch_size\x18\x05 \x01(\x05:\x03\x31\x32\x38\x12\x15\n\x07use_gpu\x18\x06 \x01(\x08:\x04true\x12\x16\n\x0bnum_workers\x18\x07 \x01(\x05:\x01\x34\x12\x16\n\nprint_freq\x18\x08 \x01(\x05:\x02\x32\x30\x12!\n\x08log_file\x18\t \x01(\t:\x0f\x63heckpoints/log\x12\x1f\n\x0bresult_file\x18\n \x01(\t:\nresult.csv\x12\x15\n\tmax_epoch\x18\x0b \x01(\x05:\x02\x31\x30\x12\x10\n\x02lr\x18\x0c \x01(\x02:\x04\x30.01\x12\x16\n\x08lr_decay\x18\r \x01(\x02:\x04\x30.95\x12\x1c\n\x0cweight_decay\x18\x0e \x01(\x02:\x06\x30.0001\x12\x1b\n\nvisdom_env\x18\x0f \x01(\t:\x07\x64\x65\x66\x61ult\x12\x0f\n\x04mode\x18\x10 \x01(\x05:\x01\x31\x12#\n\x0e\x63heckpoint_dir\x18\x11 \x01(\t:\x0b\x63heckpoints')
)




_TRAINCONFIG = _descriptor.Descriptor(
  name='TrainConfig',
  full_name='protos.TrainConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='protos.TrainConfig.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("renet101").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train_data_root', full_name='protos.TrainConfig.train_data_root', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("./data/train").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_data_root', full_name='protos.TrainConfig.test_data_root', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("./data/test").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='load_model_path', full_name='protos.TrainConfig.load_model_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("checkpoints/model.pth").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='protos.TrainConfig.batch_size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=128,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='use_gpu', full_name='protos.TrainConfig.use_gpu', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_workers', full_name='protos.TrainConfig.num_workers', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='print_freq', full_name='protos.TrainConfig.print_freq', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=20,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_file', full_name='protos.TrainConfig.log_file', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("checkpoints/log").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_file', full_name='protos.TrainConfig.result_file', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("result.csv").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_epoch', full_name='protos.TrainConfig.max_epoch', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lr', full_name='protos.TrainConfig.lr', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.01),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lr_decay', full_name='protos.TrainConfig.lr_decay', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.95),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight_decay', full_name='protos.TrainConfig.weight_decay', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visdom_env', full_name='protos.TrainConfig.visdom_env', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("default").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='protos.TrainConfig.mode', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkpoint_dir', full_name='protos.TrainConfig.checkpoint_dir', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("checkpoints").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=529,
)

DESCRIPTOR.message_types_by_name['TrainConfig'] = _TRAINCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainConfig = _reflection.GeneratedProtocolMessageType('TrainConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRAINCONFIG,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:protos.TrainConfig)
  ))
_sym_db.RegisterMessage(TrainConfig)


# @@protoc_insertion_point(module_scope)
